name: Build and Deploy to GCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker Image to GCR
        run: |
          docker build -t gcr.io/my-mern-app-venkatesh-01/my-mern-app:latest .
          docker push gcr.io/my-mern-app-venkatesh-01/my-mern-app:latest

